from typing import TypedDict, Dict, Any, Optional

class SolverState(TypedDict):
    """
    Represents the state of the auto-solver agent.
    """
    # Initial input
    problem_statement: str
    num_test_generations: int  # How many batches of test cases to generate
    max_iterations: int        # Max refinement loops

    # --- Code generated by initial nodes ---
    bruteforce_code: Optional[str]
    test_generator_code: Optional[str]
    solution_code: Optional[str]

    # --- State for the refinement loop ---
    test_results: Optional[Dict[str, Any]]
    iteration_count: int

    # --- Final output ---
    final_verdict: str